# Generated by Django 4.1.1 on 2022-09-25 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Марка')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Наименование')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=25, verbose_name='Фамилия')),
                ('address', models.CharField(max_length=250, verbose_name='Адрес')),
                ('phone', models.CharField(max_length=15, verbose_name='Номер телефона')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Поставщик')),
                ('address', models.CharField(max_length=250, verbose_name='Адрес')),
                ('inn', models.CharField(max_length=10, verbose_name='ИНН')),
                ('phone', models.CharField(max_length=15, verbose_name='Номер телефона')),
            ],
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Производитель')),
                ('address', models.CharField(max_length=250, verbose_name='Адрес')),
                ('inn', models.CharField(max_length=10, verbose_name='ИНН')),
                ('phone', models.CharField(max_length=15, verbose_name='Номер телефона')),
            ],
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Модель')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.brand')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_order', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.client')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.SlugField(verbose_name='Артикул')),
                ('name', models.CharField(max_length=150, verbose_name='Наименование')),
                ('price', models.DecimalField(decimal_places=10, max_digits=10, verbose_name='Цена')),
                ('description', models.TextField(verbose_name='Описание')),
                ('amount', models.IntegerField(verbose_name='Количество')),
                ('foto', models.ImageField(upload_to='photos/')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.category')),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.contractor')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.manufacturer')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.model')),
            ],
        ),
        migrations.CreateModel(
            name='Order_Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='Количество')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.product')),
            ],
        ),
    ]
